#include "GameplayHooks.hpp"
#include "WrappedManager.hpp"
#include "Logging.hpp"

#include "beatsaber-hook/shared/utils/hooking.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils.hpp"

// These two headers are generated by `qpm restore` into extern/includes once
// you've restored dependencies against your 1.40.8 codegen. Their exact path
// has been stable across recent Beat Saber Quest versions, but double check
// after restoring.
#include "GlobalNamespace/StandardLevelScenesTransitionSetupDataSO.hpp"
#include "GlobalNamespace/LevelCompletionResults.hpp"
#include "GlobalNamespace/IDifficultyBeatmap.hpp"
#include "GlobalNamespace/IPreviewBeatmapLevel.hpp"

#include <chrono>
#include <string>

using namespace GlobalNamespace;

namespace BeatSaberWrapped::Hooks {

    static std::string s_currentLevelId;
    static std::string s_currentSongName;
    static std::string s_currentSongAuthor;
    static std::chrono::steady_clock::time_point s_sessionStart;
    static bool s_sessionActive = false;

    // ---- Hook 1: song/level session starts -------------------------------
    // Fires once per level load, right as the gameplay scene is set up. This
    // is where we grab the song's metadata and start our stopwatch.
    //
    // VERIFY AGAINST YOUR CODEGEN: `StandardLevelScenesTransitionSetupDataSO::Init`
    // has had a couple of different overloads/parameter orders across Beat
    // Saber versions (extra environment/modifier params get added sometimes).
    // Open extern/includes/GlobalNamespace/StandardLevelScenesTransitionSetupDataSO.hpp
    // after `qpm restore` and match this signature to the real one — the
    // *body* below doesn't need to change, only the parameter list.
    MAKE_HOOK_MATCH(StandardLevelScenesTransitionSetupDataSO_Init,
                    &StandardLevelScenesTransitionSetupDataSO::Init,
                    void,
                    StandardLevelScenesTransitionSetupDataSO* self,
                    Il2CppString* gameMode,
                    IDifficultyBeatmap* difficultyBeatmap,
                    IPreviewBeatmapLevel* previewBeatmapLevel,
                    GameplayModifiers* gameplayModifiers,
                    PlayerSpecificSettings* playerSpecificSettings,
                    PracticeSettings* practiceSettings,
                    Il2CppString* backButtonText,
                    bool useTestNoteCutSoundEffects,
                    bool startPaused) {

        StandardLevelScenesTransitionSetupDataSO_Init(self, gameMode, difficultyBeatmap,
            previewBeatmapLevel, gameplayModifiers, playerSpecificSettings,
            practiceSettings, backButtonText, useTestNoteCutSoundEffects, startPaused);

        if (previewBeatmapLevel != nullptr) {
            s_currentLevelId = std::string(to_utf8(csstrtostr(previewBeatmapLevel->get_levelID())));
            s_currentSongName = std::string(to_utf8(csstrtostr(previewBeatmapLevel->get_songName())));
            s_currentSongAuthor = std::string(to_utf8(csstrtostr(previewBeatmapLevel->get_songAuthorName())));
        } else {
            s_currentLevelId = "unknown";
            s_currentSongName = "Unknown Song";
            s_currentSongAuthor = "Unknown Author";
        }

        s_sessionStart = std::chrono::steady_clock::now();
        s_sessionActive = true;
    }

    // ---- Hook 2: session ends (finished OR quit early) --------------------
    // `Finish` fires when the gameplay scene tears down, whether the player
    // cleared the song, failed, or bailed back to the menu — which is exactly
    // what we want, since "minutes played" should count partial attempts too.
    //
    // VERIFY AGAINST YOUR CODEGEN: same caveat as above — confirm the
    // parameter list of `Finish` against your restored header.
    MAKE_HOOK_MATCH(StandardLevelScenesTransitionSetupDataSO_Finish,
                    &StandardLevelScenesTransitionSetupDataSO::Finish,
                    void,
                    StandardLevelScenesTransitionSetupDataSO* self,
                    LevelCompletionResults* results) {

        if (s_sessionActive) {
            double playedSeconds = std::chrono::duration<double>(
                std::chrono::steady_clock::now() - s_sessionStart).count();

            BeatSaberWrapped::WrappedManager::Get().LogSession(
                s_currentLevelId, s_currentSongName, s_currentSongAuthor, playedSeconds);

            s_sessionActive = false;
        }

        StandardLevelScenesTransitionSetupDataSO_Finish(self, results);
    }

    void InstallGameplayHooks() {
        INSTALL_HOOK(BeatSaberWrapped::getLogger(), StandardLevelScenesTransitionSetupDataSO_Init);
        INSTALL_HOOK(BeatSaberWrapped::getLogger(), StandardLevelScenesTransitionSetupDataSO_Finish);
    }
}
